"""MedMIG-CR Phase 2 Retrieval Implementation Summary."""


def main() -> None:
    print("=" * 80)
    print("MedMIG-CR Phase 2 RETRIEVAL - IMPLEMENTATION SUMMARY")
    print("=" * 80)
    print()
    print("MODULES IMPLEMENTED:")
    print("  1. graph_store.py")
    print("     - Loads CSR graph, node embeddings (64-dim), degrees, mappings")
    print("     - Supports bidirectional neighbor retrieval (out/in edges)")
    print()
    print("  2. scoring.py")
    print("     - Cosine similarity: measures semantic relevance to interest vector")
    print("     - Degree penalty: log(degree + 1) to avoid hub nodes")
    print("     - Combined score: α·cosine(embedding, interest) - β·log(degree+1)")
    print()
    print("  3. beam_search.py")
    print("     - Multi-hop semantic beam search over graph")
    print("     - Per-path tracking: current_node, full_path, cumulative_score")
    print("     - Cycle avoidance & path deduplication")
    print("     - Expands both outgoing and incoming neighbors")
    print()
    print("  4. retrieval_engine.py")
    print("     - Per-interest vector beam search (max 3 paths per interest)")
    print("     - Deduplicates paths across multiple interests")
    print("     - Ranks candidate diseases by endpoint score")
    print("     - Computes metrics: path_diversity, hub_ratio, latency")
    print()
    print("  5. subgraph_builder.py")
    print("     - Reconstructs retrieved subgraph (nodes, edges, relations)")
    print("     - Aggregates relation labels across paths")
    print()
    print("  6. phase2_retrieve_query.py")
    print("     - MAIN ENTRY POINT: query-driven retrieval")
    print("     - Loads seed symptoms from query_nodes.csv")
    print("     - Outputs paths with node types")
    print()
    print("=" * 80)
    print("HOW TO RUN")
    print("=" * 80)
    print()
    print("BASIC USAGE:")
    print("  cd 'Subgraph retrieval'")
    print("  python phase2_retrieve_query.py Q0000005")
    print()
    print("WITH CUSTOM PARAMETERS:")
    print("  python phase2_retrieve_query.py Q0000005 --max_hops=5 --beam_width=32 --interest_count=3")
    print()
    print("PARAMETER MEANINGS:")
    print("  query_id           : Query ID from processed_medmigcr_dataset/query_nodes.csv")
    print("  --max_hops         : Maximum traversal depth in graph (default=5)")
    print("  --beam_width       : Top-K paths to keep per hop (default=32)")
    print("  --interest_count   : Number of interest vectors to generate (default=3)")
    print()
    print("=" * 80)
    print("OUTPUT FILES")
    print("=" * 80)
    print()
    print("  phase2_retrieval_<QUERY_ID>.json")
    print("    - nodes: [node_id, node_name]")
    print("    - edges: [source, target, relations]")
    print("    - paths: [score, path_nodes_list]")
    print()
    print("  phase2_retrieval_<QUERY_ID>_summary.txt")
    print("    - Query details (seed symptoms)")
    print("    - Retrieval parameters")
    print("    - Metrics (path_diversity, hub_ratio, latency)")
    print("    - Top 50 candidate diseases with scores")
    print("    - All retrieved paths with full traversals")
    print()
    print("=" * 80)
    print("VECTOR SPACE ALIGNMENT")
    print("=" * 80)
    print()
    print("  Node embeddings:    64-dim (Node2Vec trained on PrimeKG)")
    print("  Interest vectors:   64-dim (Clinical MIND from symptom sequences)")
    print("  → Same vector space for valid cosine similarity")
    print()
    print("=" * 80)
    print("EXAMPLE QUERY RUNS")
    print("=" * 80)
    print()
    print("  Query Q0000005 (3 symptoms: Splenomegaly, Hepatic failure, Intrahepatic cholestasis)")
    print("    python phase2_retrieve_query.py Q0000005 --interest_count=3")
    print()
    print("  Query Q0000001 (7 symptoms: Hypotonia, Hyperhidrosis, Keratosis pilaris, ...)")
    print("    python phase2_retrieve_query.py Q0000001 --max_hops=6 --interest_count=5")
    print()
    print("  Shallow retrieval (2 hops, narrow beam)")
    print("    python phase2_retrieve_query.py Q0000010 --max_hops=2 --beam_width=16")
    print()
    print("=" * 80)


if __name__ == "__main__":
    main()
